### ISSUE TITLE
Location Information

### ISSUE THREAD

**Issue by fakrul** [OpenBMP/openbmp#12]
How does the location information works? The other geo location says my IP is from AU, but San Jose/New York. Also tried importing GEOIP List, but no luck.

**Comment by TimEvens** [comment]
You can update geo-coding using the docker openbmp/ui as well as via direct DB updates.  There are several ways to update the DB geo_ip table.  Below is a simple method to do that. 

* Use http://www.latlong.net to get the latitude and longitude
* Use the below CSV format to update a file such as geo-code-data.csv
   ip_start,ip_end,city,state,country,latitude,longitude,organization_name,isp_name

```awk
awk -F ',' '{ 
      if (index($1,"."))
         addr_type = "ipv4";
      else
         addr_type = "ipv6";

      if ($0 !~ /[:space]*#.*/ && length($1) > 0)
        printf("REPLACE INTO geo_ip (addr_type,ip_start,ip_end,city,stateprov,country, \
                    latitude,longitude,organization_name,isp_name,timezone_offset,timezone_name) \
                values (\"%s\",inet6_aton(\"%s\"),inet6_aton(\"%s\"),\"%s\",\"%s\",\"%s\",%f,%f,\"%s\",\"%s\",\"%d\", \"%s\");\n",
            addr_type, $1, $2, $3, $4, $5, $6, $7, $8, $9,$10,gsub(/\n/, "", $11));
  }' geo-code-data.csv
```
