### ISSUE TITLE
Export feature

### ISSUE THREAD

**Issue by fakrul** [OpenBMP/openbmp#13]
Feature like export table data to XLS/CSV will be really helpful for further analysis

**Comment by TimEvens** [comment]
There is the file consumer which can do that.  Did you want to run without Kafka?

**Comment by TimEvens** [comment]
Normally we do this via a Kafka consumer, such as the openbmp-file-consumer, which can be extended to create CSV log files... But there are some use-cases where we don't want to use Kafka or any other consumer for debugging.   In this case, it might be good to add a log option to log afi/safi's in CSV format.  Alternatively, you can use -debug -dbgp to get all details without requiring any consumers.

**Comment by fakrul** [comment]
'-debug -dbgp' looks better. thanks.
