### ISSUE TITLE
Web UI password change problem

### ISSUE THREAD

**Issue by agallo** [OpenBMP/openbmp#29]
If you try to modify a user's password by double clicking in the password field, but do not make any changes (say, by clicking elsewhere on the screen or pressing tab), the hash of the previous password becomes the user's new plaintext password.  

Example:
If a user has a plaintext password of `mypasswd`, the displayed hash starts with `*85E26B8....`
If you double click on this field, but do not make a change, then the hash `*85E26B8....` becomes the user's new password (which of course hashes to something different, in this case `*26347...`)

The behavior should be to not change the password.

**Comment by TimEvens** [comment]
issue is related to UI, not this repo.  The repo was moved to github.com/snas/ui
