### ISSUE TITLE
Double number of BMP speakers

### ISSUE THREAD

**Issue by vladsker** [OpenBMP/openbmp#33]
Hi, team,

first of all, thanks for great project.

I'm currently evaluating openBMP setup. We've installed two collectors on two different servers to load balance. And if looks like after the same speaker moves from one openbmp collector to another, it generates different hash to it and so, the same router appears twice in the table:

mysql> select * from routers;
+----------------------------------+--------------------------------------+----------------+-----------+----------------------------+---------------------+-------------+-----------+------------------+------------------------------------------+-----------+-----------+--------------+----------------------------------+--------+
| hash_id                          | name                                 | ip_address     | router_AS | timestamp                  | description         | isConnected | isPassive | term_reason_code | term_reason_text                         | term_data | init_data | geo_ip_start | collector_hash_id                | bgp_id |
+----------------------------------+--------------------------------------+----------------+-----------+----------------------------+---------------------+-------------+-----------+------------------+------------------------------------------+-----------+-----------+--------------+----------------------------------+--------+

| 299f3867d02084a17996c08eb4575fde | AMS4-BK-INTMX480-02                  | 10.193.131.111 |      NULL | 2017-01-09 11:49:35.797575 |                     |           0 |         0 |            65534 | ERROR: Cannot read v3 BMP common header. |           |           | NULL         | 025afb2299ca3dfb4394bc15ec8a44ca |        |
| 5056616ed30c6706d0cdfd767ff89125 | AMS4-BK-INTMX480-01                  | 10.193.131.93  |      NULL | 2017-01-09 12:47:07.294717 | AMS4-BK-INTMX480-01 |           1 |         0 |                0 |                                          |           |           | NULL         | b95c837efc08b628eb6162ba6f1afd8a |        |
| df0975c55d0fb7846919c45e044bf9a4 | AMS4-BK-INTMX480-01                  | 10.193.131.93  |      NULL | 2017-01-09 11:50:07.511103 |                     |           0 |         0 |            65534 | ERROR: Cannot read v3 BMP common header. |           |           | NULL         | 025afb2299ca3dfb4394bc15ec8a44ca

Is it expected behavior?

**Comment by TimEvens** [comment]
Thanks!   The current hashing includes the collector hash so that a message received from one collector is unique to another.  If you want both collectors to appear as the same, then you can change the **openbmpd.conf** ```base.admin_id``` to something that is the same on both collectors.   The default of **hostname** means that the collector will use the local hostname.  If you changed it to "collector" or something like that, it'll then be the same hash_id when you move it from collector A to B.  

Does that work?

**Comment by vladsker** [comment]
Thanks for explanation. Looks like it works.

**Comment by TimEvens** [comment]
Cool.  closing for now.
