### ISSUE TITLE
openBMP reports down state for connected BGP peer

### ISSUE THREAD

**Issue by vladsker** [OpenBMP/openbmp#34]
Hi, mates,

We are evaluating openBMP in a big Internet environment (~700 of peers). For some of the peers that are up opnebmp reports down stage.

Can you advise on this?

mysql> select * from bgp_peers where peer_addr = "80.249.208.255";
+----------------------------------+----------------------------------+---------+--------+----------------+----------------+----------------+---------+-------+-------------+----------------------------+-------------+--------------+----------------+---------------+------------+-----------------+-----------+-------------+------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------------+--------------+-----------------+------------+
| hash_id                          | router_hash_id                   | peer_rd | isIPv4 | peer_addr      | name           | peer_bgp_id    | peer_as | state | isL3VPNpeer | timestamp                  | isPrePolicy | geo_ip_start | local_ip       | local_bgp_id  | local_port | local_hold_time | local_asn | remote_port | remote_hold_time | sent_capabilities                                                                                                                | recv_capabilities                                                                                                                | bmp_reason | bgp_err_code | bgp_err_subcode | error_text |
+----------------------------------+----------------------------------+---------+--------+----------------+----------------+----------------+---------+-------+-------------+----------------------------+-------------+--------------+----------------+---------------+------------+-----------------+-----------+-------------+------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------------+--------------+-----------------+------------+
| 8c21ff121b323ca6f99e08066bfe7fed | 5056616ed30c6706d0cdfd767ff89125 | 0:0     |      1 | 80.249.208.255 | rs1.ams-ix.net | 80.249.208.255 |    6777 |     0 |           0 | 2017-01-09 14:08:49.667696 |           1 | NULL         | 80.249.210.198 | 10.252.128.22 |      50198 |              90 |     43996 |         179 |              240 | MPBGP (1) : afi=1 safi=1 : Unicast IPv4, Route Refresh Old (128), Route Refresh (2), Graceful Restart (64), 4 Octet ASN (65), 71 | MPBGP (1) : afi=1 safi=1 : Unicast IPv4, Route Refresh (2), Graceful Restart (64), 4 Octet ASN (65), Route Refresh Enhanced (70) |          0 |            0 |               0 |            |
+----------------------------------+----------------------------------+---------+--------+----------------+----------------+----------------+---------+-------+-------------+----------------------------+-------------+--------------+----------------+---------------+------------+-----------------+-----------+-------------+------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------------+--------------+-----------------+------------+
1 rows in set (0.01 sec)

mysql> select * from peer_up_events where peer_hash_id = "8c21ff121b323ca6f99e08066bfe7fed";
+------+----------------------------------+----------------+---------------+------------+-----------------+-----------+-------------+------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------+
| id   | peer_hash_id                     | local_ip       | local_bgp_id  | local_port | local_hold_time | local_asn | remote_port | remote_hold_time | sent_capabilities                                                                                                                | recv_capabilities                                                                                                                | timestamp                  |
+------+----------------------------------+----------------+---------------+------------+-----------------+-----------+-------------+------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------+
| 1431 | 8c21ff121b323ca6f99e08066bfe7fed | 80.249.210.198 | 10.252.128.22 |      50198 |              90 |     43996 |         179 |              240 | MPBGP (1) : afi=1 safi=1 : Unicast IPv4, Route Refresh Old (128), Route Refresh (2), Graceful Restart (64), 4 Octet ASN (65), 71 | MPBGP (1) : afi=1 safi=1 : Unicast IPv4, Route Refresh (2), Graceful Restart (64), 4 Octet ASN (65), Route Refresh Enhanced (70) | 2017-01-09 11:50:38.000000 |
+------+----------------------------------+----------------+---------------+------------+-----------------+-----------+-------------+------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------------+
1 row in set (0.02 sec)

mysql> select * from peer_down_events where peer_hash_id = "8c21ff121b323ca6f99e08066bfe7fed";
Empty set (0.01 sec)

**Comment by TimEvens** [comment]
Are you using the latest mysql-consumer?  The docker AIO and mysql container were updated on 12/20/2016 to help resolve this issue.  If you haven't done a docker pull since 12/20, try an upgrade first. 

Which BGP platform/implementation are you using (e.g. IOS XE, XR, JunOS, goBGP) ?    In IOS XR and XE, you should configure the ```initial-delay``` and ``` initial-refresh delay``` to 30 or more seconds.  This ensures that the ROUTER INIT and PEER UP messages are spaced a bit before route monitor messages come in. 

I'm in Pacific Time.   Tomorrow I'll add a comment with the SQL query to fix the peer states, which is a workaround.

**Comment by vladsker** [comment]
Thanks. Give me some time to update and check this. I will update you soon.
