### ISSUE TITLE
Jenkins SSL certificate

### ISSUE THREAD

**Issue by DamianZaremba** [OpenBMP/openbmp#35]
Would it be possible to put a 'real' SSL certificate on the Jenkins instance, or alternately upload the 'release' builds to Github for all components?

Background; we run the collector on dedicated hardware, then the other components in individual vms.

Problem; our packaging framework has to pass through a set of proxies to download build artifacts, for security reasons these deny connects to sites with invalid SSL certificates.

This is currently handled by manually downloaded the artifacts, which is not optimal and potentially can be intercepted.

Is this something you can consider?

Thanks

- Damian

**Comment by TimEvens** [comment]
will change shortly.

**Comment by TimEvens** [comment]
Updated certificate.  Can you verify it's working for you?

**Comment by DamianZaremba** [comment]
Sorry for the delay in coming back to you on this....

It looks like our proxies are happy, but Chrome is not =\

It's reporting the certificate is revoked (StartCom Class 1 DV Server CA is invalid) - perhaps you're missing an intermediary certificate in the bundle?

**Comment by TimEvens** [comment]
it should have been there.  hemmm.. will check that again.  Thanks.

**Comment by TimEvens** [comment]
Looks like Startcom is no longer a trusted CA.  I've changed to letsencrypt. Can you try again? 

Thanks,
Tim

**Comment by DamianZaremba** [comment]
Looks good! Thanks
