### ISSUE TITLE
how can you tell: pre-policy or post-policy

### ISSUE THREAD

**Issue by nskalis** [OpenBMP/openbmp#37]
Hi,

I was wondering if you could help me and share the way how to check in the database
the prefixes that belong to pre-policy and which ones belong to the post-policy ?

Both, pre|post-policy have been configuring on the router.

In other words, when the 'L' bit is set ? https://tools.ietf.org/html/rfc7854#section-4.6

Many Thanks,
Nikos

**Comment by TimEvens** [comment]
The L flag is set in the peer header, which is present in many BMP messages, including the peer UP.   Both the **bgp_peers** and **rib** tables have a boolean field **"isPrePolicy"** to indicate if the record/entry is pre or post policy.  A value of **1** indicates pre-policy and a value of **0** indicates post-policy.    

Based on testing with JunOS 14.2R6.5, it will set pre-policy for the PEER UP but will send both pre and post policy route-monitor messages.  This means the peer table (v_peers and bgp_peers) will indicate pre-policy, but the **rib** table will indicate both **pre-policy** and **post-policy**. 

I just noticed that the **v_routes** VIEW is missing isPrePolicy, so I'll add this in the next DB update to the mysql-consumer.  For now, you can apply the following to update your VIEW

```sql
drop view v_routes;
CREATE  VIEW v_routes AS
       SELECT  if (length(rtr.name) > 0, rtr.name, rtr.ip_address) AS RouterName,
                if(length(p.name) > 0, p.name, p.peer_addr) AS PeerName,
                r.prefix AS Prefix,r.prefix_len AS PrefixLen,
                path.origin AS Origin,r.origin_as AS Origin_AS,path.med AS MED,
                path.local_pref AS LocalPref,path.next_hop AS NH,path.as_path AS AS_Path,
                path.as_path_count AS ASPath_Count,path.community_list AS Communities,
                path.ext_community_list AS ExtCommunities,path.cluster_list AS ClusterList,
                path.aggregator AS Aggregator,p.peer_addr AS PeerAddress, p.peer_as AS PeerASN,r.isIPv4 as isIPv4,
                p.isIPv4 as isPeerIPv4, p.isL3VPNpeer as isPeerVPN,
                r.timestamp AS LastModified, r.first_added_timestamp as FirstAddedTimestamp,r.prefix_bin as prefix_bin,
                r.path_id, r.labels,
                r.hash_id as rib_hash_id,
                r.path_attr_hash_id as path_hash_id, r.peer_hash_id, rtr.hash_id as router_hash_id,r.isWithdrawn,
                r.prefix_bits,r.isPrePolicy,r.isAdjRibIn
        FROM bgp_peers p JOIN rib r ON (r.peer_hash_id = p.hash_id)
            JOIN path_attrs path ON (path.hash_id = r.path_attr_hash_id and path.peer_hash_id = r.peer_hash_id)
            JOIN routers rtr ON (p.router_hash_id = rtr.hash_id)
       WHERE r.isWithdrawn = False;

```

An example to show post-policy RIB is: 

```sql
select routername,peername,prefix,prefixlen,as_path,isprepolicy from v_routes 
     where peername = 'tara-wsp-nrt-9k-4' and isprepolicy = 0;
```

An example to show pre-policy RIB is:
```sql
select routername,peername,prefix,prefixlen,as_path,isprepolicy from v_routes 
      where peername = 'tara-wsp-nrt-9k-4' and isprepolicy = 1;
```

> ### NOTE: You should use the peer_hash_id in the WHERE clause since that will use indexes.  The example above is only a quick example. 

Please let me know if this works.

**Comment by nskalis** [comment]
@TimEvens thanks a lot for the detailed answer I can confirm that is works. Thanks for th prompt reply.
