### ISSUE TITLE
Removing routers from the database

### ISSUE THREAD

**Issue by agallo** [OpenBMP/openbmp#42]
Is there a way to remove a router that is no longer sending BMP?

I've got a router that is no longer sending information to OpenBMP, so it is showing as a down router.

Thank you.

**Comment by TimEvens** [comment]
Yes, you can use the following to completely remove a router from the DB.  The steps below can be automated... If you have time to contribute, submit a pull request with script or stored procedure to remove a router. If you submit a stored procedure, can you submit that to ***openbmp-mysql-consumer** repo?  

### Remove Router and all peers associated to the router

1. get the **router hash id** by using ```select hash_id from routers where name = 'router name'```

The following steps use **64742b7e27f272bf96e0473a0d26fe52** as the example hash_id of the router to remove. 

2. Remove RIB entries related to router peers

```sql
delete r from rib r join bgp_peers p ON (r.peer_hash_id = p.hash_id) where p.router_hash_id = '64742b7e27f272bf96e0473a0d26fe52';
```

3. Remove path attributes related to the router peers

```sql
delete a from path_attrs a join bgp_peers p ON (a.peer_hash_id = p.hash_id) where p.router_hash_id = '64742b7e27f272bf96e0473a0d26fe52';
```

4. Remove bgp peers related to router

```sql
delete from bgp_peers where router_hash_id = '64742b7e27f272bf96e0473a0d26fe52';
```

5. Remove router 

```sql
delete from routers where hash_id = '64742b7e27f272bf96e0473a0d26fe52';
```

**Comment by agallo** [comment]
Thank you, Tim!  I'll see if I can learn enough about stored procedures to make a contribution.

**Comment by agallo** [comment]
Reopening to submit a pull request with the following MySQL procedure:


DELIMITER //
DROP PROCEDURE IF EXISTS DeleteRouter;
CREATE PROCEDURE DeleteRouter
(IN rname varchar(200))
BEGIN
  DECLARE hid char(32);
  SELECT hash_id INTO hid FROM routers WHERE name = rname;
  DELETE r FROM rib r JOIN bgp_peers p ON (r.peer_hash_id = p.hash_id) WHERE p.router_hash_id = hid;
  DELETE a FROM path_attrs a JOIN bgp_peers p ON (a.peer_hash_id = p.hash_id) WHERE p.router_hash_id = hid;
  DELETE FROM bgp_peers WHERE router_hash_id = hid;
  DELETE FROM routers WHERE hash_id = hid;
END //
DELIMITER ;

**Comment by TimEvens** [comment]
stored procedure added.
