### ISSUE TITLE
Issue Compiling source during OpenBMP installation

### ISSUE THREAD

**Issue by daniel-ibrowse** [OpenBMP/openbmp#46]
Hello,

I'm new working with OpenBMP, I'm trying to install it in my server Dell 210, everything went smooth until the compiling part, I get the next error:

daniel@ubuntu:~/openbmp/build$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.58.0
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.0.2g", minimum required is "1")
-- Performing Test SUPPORTS_STD_CXX11
-- Performing Test SUPPORTS_STD_CXX11 - Success
-- Performing Test SUPPORTS_STD_CXX01
-- Performing Test SUPPORTS_STD_CXX01 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/daniel/openbmp/build

daniel@ubuntu:~/openbmp/build$ make
Scanning dependencies of target openbmpd
[  4%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bmp/BMPListener.cpp.o
[  8%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bmp/BMPReader.cpp.o
[ 12%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/kafka/MsgBusImpl_kafka.cpp.o
[ 16%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/kafka/KafkaEventCallback.cpp.o
[ 20%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/kafka/KafkaDeliveryReportCallback.cpp.o
[ 24%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/kafka/KafkaTopicSelector.cpp.o
[ 28%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/kafka/KafkaPeerPartitionerCallback.cpp.o
[ 32%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/openbmp.cpp.o
[ 36%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bmp/parseBMP.cpp.o
[ 40%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/md5.cpp.o
[ 44%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/Logger.cpp.o
[ 48%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/Config.cpp.o
[ 52%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/client_thread.cpp.o
[ 56%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/parseBGP.cpp.o
[ 60%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/NotificationMsg.cpp.o
[ 64%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/OpenMsg.cpp.o
[ 68%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/UpdateMsg.cpp.o
[ 72%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/MPReachAttr.cpp.o
[ 76%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/MPUnReachAttr.cpp.o
[ 80%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/ExtCommunity.cpp.o
[ 84%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/AddPathDataContainer.cpp.o
[ 88%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/EVPN.cpp.o
[ 92%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/linkstate/MPLinkState.cpp.o
[ 96%] Building CXX object Server/CMakeFiles/openbmpd.dir/src/bgp/linkstate/MPLinkStateAttr.cpp.o
[100%] Linking CXX executable openbmpd
/usr/local/lib/librdkafka.a(rddl.o): In function `rd_dl_error':
/home/daniel/librdkafka/src/rddl.c:51: undefined reference to `dlerror'
/usr/local/lib/librdkafka.a(rddl.o): In function `rd_dl_open':
/home/daniel/librdkafka/src/rddl.c:79: undefined reference to `dlopen'
/usr/local/lib/librdkafka.a(rddl.o): In function `rd_dl_sym':
/home/daniel/librdkafka/src/rddl.c:115: undefined reference to `dlsym'
/usr/local/lib/librdkafka.a(rddl.o): In function `rd_dl_close':
/home/daniel/librdkafka/src/rddl.c:100: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
Server/CMakeFiles/openbmpd.dir/build.make:698: recipe for target 'Server/openbmpd' failed
make[2]: *** [Server/openbmpd] Error 1
CMakeFiles/Makefile2:85: recipe for target 'Server/CMakeFiles/openbmpd.dir/all' failed
make[1]: *** [Server/CMakeFiles/openbmpd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

If you can help me out, it would be great!
Thank you for your help!

Daniel

**Comment by TimEvens** [comment]
Which version of ubuntu?   Are you using the master branch of librdkafka or a specific release?

**Comment by TimEvens** [comment]
I just checked the master branch and the error you are seeing is from the master branch addition/support of dynamically loadable plugins.  rddl.c has not been released yet in librdkafka.

We use the latest 0.9.5 release of librdkafka, which doesn't have rddl.c.  

Can you do the following and rebuild?

```
cd librdkafka
git pull
git checkout v0.9.5
configure
make install
```

**Comment by daniel-ibrowse** [comment]
I was using Ubuntu 16.04 but now I tried again in a Ubuntu 17.04 (zesty)... I get the same error in both versions and after doing the previous commands you mentioned i get the next error:

daniel@daniel-zesty:~/openbmp/build$ sudo make
[  4%] Linking CXX executable openbmpd
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x2a63): undefined reference to `LZ4F_createDecompressionContext'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x2a6e): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x2aff): undefined reference to `LZ4F_freeDecompressionContext'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x2b0c): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x2c8e): undefined reference to `LZ4F_getFrameInfo'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x2c99): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x2d0a): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x304f): undefined reference to `LZ4F_decompress'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x305a): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x3108): undefined reference to `LZ4F_freeDecompressionContext'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x3115): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x32bf): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x344a): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_messageset_handle':
(.text+0x364d): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xefd5): undefined reference to `LZ4F_compressBound'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xefe8): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf053): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf1e8): undefined reference to `LZ4F_createCompressionContext'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf1f8): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf266): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf2d5): undefined reference to `LZ4F_compressBegin'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf2e5): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf363): undefined reference to `LZ4F_compressUpdate'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf373): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf5d3): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf62b): undefined reference to `LZ4F_freeCompressionContext'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf659): undefined reference to `LZ4F_compressEnd'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf666): undefined reference to `LZ4F_isError'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf6ab): undefined reference to `LZ4F_freeCompressionContext'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf720): undefined reference to `LZ4F_getErrorName'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/librdkafka.a(rdkafka_broker.o): In function `rd_kafka_broker_thread_main':
(.text+0xf877): undefined reference to `LZ4F_getErrorName'
collect2: error: ld returned 1 exit status
Server/CMakeFiles/openbmpd.dir/build.make:698: recipe for target 'Server/openbmpd' failed
make[2]: *** [Server/openbmpd] Error 1
CMakeFiles/Makefile2:85: recipe for target 'Server/CMakeFiles/openbmpd.dir/all' failed
make[1]: *** [Server/CMakeFiles/openbmpd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
daniel@daniel-zesty:~/openbmp/build$

**Comment by TimEvens** [comment]
This was an issue with the latest librdkafka.  Should be working now.
