### ISSUE TITLE
BGP sessions record remain up when router down

### ISSUE THREAD

**Issue by bangnh1** [OpenBMP/openbmp#65]
Hi,
Thank for your repo. I'm trying to build a lab topo.
I realized that when monitoring router down, BGP sessions record still remain up state. Is it normal process?
I'm trying catch openbmpd log but it didn't receive any alert packet when router down.

![1](https://user-images.githubusercontent.com/29230374/36893094-67599518-1e39-11e8-8a43-fd42215f1530.jpg)
![2](https://user-images.githubusercontent.com/29230374/36893097-6852497e-1e39-11e8-80ad-c35ae8692e9b.jpg)

**Comment by 3fr61n** [comment]
Hi @bangnh1 

Checking your screenshot, I don't get exactly what do you mean, the column 'state' seems to match with your established sessions right? (1 means up, 0 means down)

Regards

**Comment by bangnh1** [comment]
This issue is solved. Thank for your support!
