### ISSUE TITLE
[Question]OpenBMP is not establishing BGP-LS neighborship with XR router

### ISSUE THREAD

**Issue by vphatarp** [OpenBMP/openbmp#84]
I am trying to configure BMP and BGP-LS between OpenBMP and Cisco XR router. I built OpenBMP from scratch on Centos7 and followed the configurations given in the document to configure the router for BMP and BGP-LS. BMP session is established between the 2 devices without any issue but BGP-LS neighborship is not being formed. I dont see port 179 open on the OpenBMP server and hence when the IOS-XR tries to establish BGP connection, OpenBMP server sends back a TCP Reset. I am wondering if there are some additional configurations that I am missing. Need some help in figuring this out.
Thanks.

**Comment by mziegler8888** [comment]
Same here. 
Can someone pls. let us know how to establish the BGP peer?
Thanks.

**Comment by vphatarp** [comment]
It tooks me some time figure out that BGP-LS is monitored via BMP. I earlier had the topology as follows:
Rest of the topology<--_**(igp)**_---->R1<---_**(bgp-ls/bmp)**_----->OpenBMP
I was expecting it to have 2 sessions one for BMP and one for BGP-LS. But now I have changed it to the following:
Rest of the topology<--_**(igp)**_---->R1<---_**(bgp-ls)**_----->R2<--_**(bmp)-**_--->OpenBMP
I introduced an extra Router in between and configured it so that the Link-state address family peership between R1 and R2 is monitored under BMP. Once the configuration was up, I saw all the BGP-LS data show up on OpenBMP MariaDB. Hope that helps.
