### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by abdul95** [OpenBMP/openbmp#96]
Hi all, I want to apologize if I am asking an question that has been asked many times before bit could not find anything that would work.

I am running fedora 37 have used the build.md instructions to install and reach the make of the open bmp and getting the following issue:

```
[root@fedora-big build]# make
[  4%] Linking CXX executable openbmpd
/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [Server/CMakeFiles/openbmpd.dir/build.make:471: Server/openbmpd] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: Server/CMakeFiles/openbmpd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
[root@fedora-big build]# 
```
@TimEvens I see most responses are coming from you so thought if you know the issue off the top of your head.

thank you

**Comment by luminshi** [comment]
Try install `zlib-devel` package in Fedora first and then run `make` again. Hopefully that helps.

**Comment by abdul95** [comment]
thank you @luminshi
